### ISSUE TITLE
textfield move the position when active

### ISSUE THREAD

**Issue by albertml** [Ramotion/reel-search#12]
I change the position of textfield like this:

RAMReel(frame: CGRect(origin: CGPoint(x: 0, y: 100), size: CGSize(width: self.view.bounds.width, height: 100.0)), dataSource: dataSource, placeholder: "Start by typing…")

but when typing... the position goes to bottom...

**Comment by mattvb91** [comment]
Have you solved this issue? Currently facing the same.

**Comment by andres-cianio** [comment]
Same issue here... @mattvb91 did you get it fixed ?

**Comment by mattvb91** [comment]
@AndresCianio no I had to switch to another library

**Comment by andres-cianio** [comment]
@mattvb91 may I ask which one? I really liked this one, but I don't have the time to implement it from scratch 😞

**Comment by mattvb91** [comment]
@AndresCianio  https://github.com/apasccon/SearchTextField still needed a bit of overriding the theme but at least it worked right out of the box!

**Comment by andres-cianio** [comment]
Great, thanks @mattvb91 !

**Comment by andres-cianio** [comment]
Hello @Juriv I notice the repo is still active... Any chance this can be fixed? I'm trying to get it working but to no avail. Thanks!

**Comment by RamotionRussell** [comment]
This happens because there's a keyboard listener which attempts to resize everything to keep it all centered when the iOS keyboard appears and occupies the bottom half of the screen.

I added an option to disable this resizing 88122336ab7412e14aaecd367d2e4e2d56bf8550, which hopefully will make it behave correctly when not used full screen.

Let me know if this is sufficient.

**Comment by andres-cianio** [comment]
Thanks @RamotionRussell but I've integrated a different library... When I'm done with this I'll get back and try this out, as I loved the component. Cheers!
